export const pokemonConstants = {
  GET_ALL_POKEMON: "GET_ALL_POKEMON",
  GET_DETAIL_POKEMON: "GET_DETAIL_POKEMON",
  GET_ALL_CATEGORY: "GET_ALL_CATEGORY",
  GET_ALL_TYPES: "GET_ALL_TYPES",
  POST_POKEMON: "POST_POKEMON",
  UPDATE_POKEMON: "UPDATE_POKEMON",
  DELETE_POKEMON: "DELETE_POKEMON"
};
